# Generated by Django 3.0.5 on 2022-10-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='categories',
        ),
        migrations.AddField(
            model_name='user',
            name='users',
            field=models.ManyToManyField(to='user.Category'),
        ),
    ]
